/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FaceRecConf: typeof import('./src/components/FaceRecConf.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LanguageBtn: typeof import('./src/components/LanguageBtn.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoFaces: typeof import('./src/components/VideoFaces.vue')['default']
    VideoInput: typeof import('./src/components/VideoInput.vue')['default']
    VideoOutput: typeof import('./src/components/VideoOutput.vue')['default']
  }
}
